// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBljmMqHoNCEIEheXsUlDmXCemQzjnN_SM',
    appId: '1:491800177181:android:3429d5196ea3fbed8db4f4',
    messagingSenderId: '491800177181',
    projectId: 'whatsapp-clone-702c2',
    databaseURL: 'https://whatsapp-clone-702c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatsapp-clone-702c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_HOhL1Y2W9JwS1yx7dBdonRvwMwRKY4',
    appId: '1:491800177181:ios:3e67dea3bda6ac2c8db4f4',
    messagingSenderId: '491800177181',
    projectId: 'whatsapp-clone-702c2',
    databaseURL: 'https://whatsapp-clone-702c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'whatsapp-clone-702c2.appspot.com',
    iosClientId: '491800177181-vja78trbkvgd3eifclia3c5msqkn0pnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
